<?php
// views/expenses_tracking_report.php
// Prevent any output before PDF generation
ob_start();

require('../config/class.php');
require('../helpers/fpdf/fpdf.php');

// Import components for data retrieval
require_once '../components/expenses_tracking/utilities.php';
require_once '../components/expenses_tracking/financial_stats.php';
require_once '../components/expenses_tracking/income_table.php';
require_once '../components/expenses_tracking/expenditure_table.php';

class ExpensesTrackingPDF extends FPDF {
    protected $start_date;
    protected $end_date;
    protected $category_filter;
    protected $transaction_type;

    function setFilters($start_date, $end_date, $category = 'all', $transaction_type = 'all') {
        $this->start_date = $start_date;
        $this->end_date = $end_date;
        $this->category_filter = $category;
        $this->transaction_type = $transaction_type;
    }

    function Header() {
        // Company Header with LATO SACCO styling
        $this->SetFillColor(81, 8, 126); // #51087E
        $this->Rect(0, 0, 297, 25, 'F'); // Full width colored header
        
        // Logo (if available)
        if (file_exists('../public/image/logo.jpg')) {
            $this->Image('../public/image/logo.jpg', 15, 5, 20);
        }
        
        // Company Info
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial','B', 18);
        $this->SetXY(45, 8);
        $this->Cell(200, 8, 'LATO SACCO LIMITED', 0, 1, 'L');
        
        $this->SetFont('Arial','', 12);
        $this->SetXY(45, 16);
        $this->Cell(200, 6, 'Income & Expenditure Analysis Report', 0, 1, 'L');
        
        // Report Details Box
        $this->SetY(30);
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','B', 11);
        
        // Report info box
        $this->SetFillColor(248, 249, 252);
        $this->Rect(15, 30, 267, 35, 'F');
        $this->SetXY(20, 35);
        
        // Date Range
        $formatted_start = date('M d, Y', strtotime($this->start_date));
        $formatted_end = date('M d, Y', strtotime($this->end_date));
        $period_text = "Report Period: $formatted_start to $formatted_end";
        $this->Cell(130, 6, $period_text, 0, 0, 'L');
        
        // Transaction Type Filter
        $type_text = '';
        switch($this->transaction_type) {
            case 'income_only': 
                $type_text = 'Filter: Income Transactions Only'; 
                break;
            case 'expenditure_only': 
                $type_text = 'Filter: Expenditure Transactions Only'; 
                break;
            default: 
                $type_text = 'Filter: All Transaction Types'; 
                break;
        }
        $this->Cell(110, 6, $type_text, 0, 1, 'R');
        
        $this->SetXY(20, 42);
        $this->Cell(130, 6, 'Generated: ' . date('M d, Y H:i:s'), 0, 0, 'L');
        
        // Category Filter
        $category_text = $this->category_filter === 'all' 
            ? 'Category: All Categories' 
            : 'Category: ' . ucwords(str_replace('_', ' ', $this->category_filter));
        $this->Cell(110, 6, $category_text, 0, 1, 'R');
        
        $this->SetXY(20, 49);
        $this->SetFont('Arial','', 9);
        $this->SetTextColor(80, 80, 80);
        $this->Cell(130, 6, 'Generated by: ' . ($_SESSION['username'] ?? 'System Administrator'), 0, 0, 'L');
        $this->Cell(110, 6, 'Includes: All matching income & expenditure records', 0, 1, 'R');
        
        $this->SetXY(20, 56);
        $this->Cell(130, 6, 'System: LATO Management System', 0, 0, 'L');
        $this->Cell(110, 6, 'Currency: Kenya Shillings (KSh)', 0, 1, 'R');
        
        $this->Ln(12);
    }
    
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial','I', 8);
        $this->SetTextColor(128, 128, 128);
        
        // Footer line
        $this->Line(15, $this->GetY(), 282, $this->GetY());
        $this->Ln(3);
        
        $this->Cell(0, 6, 'LATO SACCO LIMITED - Confidential Financial Report', 0, 0, 'L');
        $this->Cell(0, 6, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }

    function ExecutiveSummary($stats) {
        $this->SetFont('Arial','B', 14);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');
        $this->Ln(5);
        
        // Summary boxes in a structured layout
        $box_width = 65;
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(245, 245, 245);
        
        // Row 1 - Main Totals
        $this->Cell($box_width, 8, 'Total Income:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(0, 128, 0); // Green for income
        $this->Cell($box_width, 8, 'KSh ' . number_format($stats['total_income'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total Expenditure:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(220, 53, 69); // Red for expenditure
        $this->Cell($box_width, 8, 'KSh ' . number_format($stats['total_expenditure'], 2), 1, 1, 'R');
        $this->SetTextColor(0, 0, 0);
        
        // Row 2 - Analysis
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Net Position:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $net_color = $stats['net_position'] >= 0 ? [0, 128, 0] : [220, 53, 69];
        $this->SetTextColor($net_color[0], $net_color[1], $net_color[2]);
        $this->Cell($box_width, 8, 'KSh ' . number_format($stats['net_position'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Withdrawal Fees:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($stats['withdrawal_fees'], 2), 1, 1, 'R');
        
        // Row 3 - Profit Analysis
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total Profit:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $profit_color = $stats['total_profit'] >= 0 ? [0, 128, 0] : [220, 53, 69];
        $this->SetTextColor($profit_color[0], $profit_color[1], $profit_color[2]);
        $this->Cell($box_width, 8, 'KSh ' . number_format($stats['total_profit'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Profit Margin:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $profit_margin = $stats['total_income'] > 0 ? ($stats['total_profit'] / $stats['total_income']) * 100 : 0;
        $this->Cell($box_width, 8, number_format($profit_margin, 2) . '%', 1, 1, 'R');
        
        $this->Ln(10);
    }

    function IncomeTableHeader() {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(40, 167, 69); // Green for income
        $this->SetTextColor(255, 255, 255);
        
        $headers = [
            ['text' => 'Date', 'width' => 25],
            ['text' => 'Source Type', 'width' => 35],
            ['text' => 'Client/Group Name', 'width' => 50],
            ['text' => 'Reference No', 'width' => 30],
            ['text' => 'Amount (KSh)', 'width' => 30],
            ['text' => 'Payment Mode', 'width' => 25],
            ['text' => 'Receipt No', 'width' => 25],
            ['text' => 'Served By', 'width' => 42]
        ];
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 8, $header['text'], 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(0, 0, 0);
    }

    function ExpenditureTableHeader() {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(220, 53, 69); // Red for expenditure
        $this->SetTextColor(255, 255, 255);
        
        $headers = [
            ['text' => 'Date', 'width' => 25],
            ['text' => 'Expense Type', 'width' => 35],
            ['text' => 'Category', 'width' => 30],
            ['text' => 'Description', 'width' => 45],
            ['text' => 'Amount (KSh)', 'width' => 30],
            ['text' => 'Payment Mode', 'width' => 25],
            ['text' => 'Created By', 'width' => 35],
            ['text' => 'Status', 'width' => 37]
        ];
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 8, $header['text'], 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(0, 0, 0);
    }

    function IncomeTableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 7);
        
        // Alternate row colors
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        $this->Cell(25, 7, date('M d, Y', strtotime($data['transaction_date'])), 1, 0, 'C', true);
        $this->Cell(35, 7, substr($data['source_type'], 0, 20), 1, 0, 'L', true);
        $this->Cell(50, 7, substr($data['source_name'], 0, 30), 1, 0, 'L', true);
        $this->Cell(30, 7, substr($data['reference_no'] ?? 'N/A', 0, 15), 1, 0, 'C', true);
        
        // Amount in green
        $this->SetTextColor(0, 128, 0);
        $this->Cell(30, 7, number_format($data['amount'], 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(25, 7, substr($data['payment_mode'] ?? 'Cash', 0, 12), 1, 0, 'C', true);
        $this->Cell(25, 7, substr($data['receipt_number'] ?? 'N/A', 0, 12), 1, 0, 'C', true);
        $this->Cell(42, 7, substr($data['served_by'], 0, 20), 1, 1, 'L', true);
    }

    function ExpenditureTableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 7);
        
        // Alternate row colors
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        $this->Cell(25, 7, date('M d, Y', strtotime($data['transaction_date'])), 1, 0, 'C', true);
        $this->Cell(35, 7, substr($data['expense_type'], 0, 20), 1, 0, 'L', true);
        $this->Cell(30, 7, substr($data['expense_category'], 0, 18), 1, 0, 'L', true);
        $this->Cell(45, 7, substr($data['expense_description'], 0, 25), 1, 0, 'L', true);
        
        // Amount in red
        $this->SetTextColor(220, 53, 69);
        $this->Cell(30, 7, number_format($data['amount'], 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(25, 7, substr($data['payment_mode'] ?? 'Cash', 0, 12), 1, 0, 'C', true);
        $this->Cell(35, 7, substr($data['created_by'], 0, 18), 1, 0, 'L', true);
        
        // Status with color coding
        $status_color = $data['status'] === 'Completed' ? [0, 128, 0] : [255, 140, 0];
        $this->SetTextColor($status_color[0], $status_color[1], $status_color[2]);
        $this->Cell(37, 7, $data['status'], 1, 1, 'C', true);
        $this->SetTextColor(0, 0, 0);
    }

    function TotalRow($label, $total_amount, $record_count, $color_rgb) {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor($color_rgb[0], $color_rgb[1], $color_rgb[2]);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(60, 9, $label . ' TOTALS', 1, 0, 'L', true);
        $this->Cell(50, 9, $record_count . ' Records', 1, 0, 'C', true);
        $this->Cell(40, 9, 'Total Amount:', 1, 0, 'R', true);
        $this->Cell(40, 9, 'KSh ' . number_format($total_amount, 2), 1, 0, 'R', true);
        $this->Cell(72, 9, '', 1, 1, 'C', true); // Filler
        
        $this->SetTextColor(0, 0, 0);
    }
}

// Get filter parameters
$filters = ExpensesUtilities::initializeFilters();
$start_date = $filters['start_date'];
$end_date = $filters['end_date'];
$category = $filters['category'];
$transaction_type = isset($_GET['transaction_type']) ? $_GET['transaction_type'] : 'all';

// Initialize database and components
$db = new db_class();
$financialStats = new FinancialStats($db);
$incomeTable = new IncomeTable($db, $start_date, $end_date, $category, $transaction_type);
$expenditureTable = new ExpenditureTable($db, $start_date, $end_date, $category, $transaction_type);

// Get data
$stats = $financialStats->calculateStats($start_date, $end_date, $category, $transaction_type);

// Get detailed data using reflection to access private methods
$incomeReflection = new ReflectionClass($incomeTable);
$incomeMethod = $incomeReflection->getMethod('getDetailedIncomeData');
$incomeMethod->setAccessible(true);
$income_data = $incomeMethod->invoke($incomeTable);

$expenditureReflection = new ReflectionClass($expenditureTable);
$expenditureMethod = $expenditureReflection->getMethod('getDetailedExpenditureData');
$expenditureMethod->setAccessible(true);
$expenditure_data = $expenditureMethod->invoke($expenditureTable);

// Initialize PDF
$pdf = new ExpensesTrackingPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->setFilters($start_date, $end_date, $category, $transaction_type);

// Start generating PDF
$pdf->AddPage();

// Add executive summary
$pdf->ExecutiveSummary($stats);

// Income Section
if ($transaction_type !== 'expenditure_only' && !empty($income_data)) {
    $pdf->SetFont('Arial','B', 12);
    $pdf->SetTextColor(40, 167, 69);
    $pdf->Cell(0, 10, 'INCOME TRANSACTIONS DETAIL', 0, 1, 'L');
    $pdf->Ln(3);
    
    $pdf->IncomeTableHeader();
    
    $row_count = 0;
    foreach ($income_data as $row_data) {
        // Check if we need a new page
        if ($pdf->GetY() > 180) {
            $pdf->AddPage();
            $pdf->IncomeTableHeader();
        }
        
        $pdf->IncomeTableRow($row_data, $row_count % 2 == 0);
        $row_count++;
    }
    
    // Add income totals
    if ($pdf->GetY() > 175) {
        $pdf->AddPage();
    }
    $pdf->Ln(3);
    $pdf->TotalRow('INCOME', $stats['total_income'], count($income_data), [40, 167, 69]);
    $pdf->Ln(10);
}

// Expenditure Section
if ($transaction_type !== 'income_only' && !empty($expenditure_data)) {
    $pdf->SetFont('Arial','B', 12);
    $pdf->SetTextColor(220, 53, 69);
    $pdf->Cell(0, 10, 'EXPENDITURE TRANSACTIONS DETAIL', 0, 1, 'L');
    $pdf->Ln(3);
    
    $pdf->ExpenditureTableHeader();
    
    $row_count = 0;
    foreach ($expenditure_data as $row_data) {
        // Check if we need a new page
        if ($pdf->GetY() > 180) {
            $pdf->AddPage();
            $pdf->ExpenditureTableHeader();
        }
        
        $pdf->ExpenditureTableRow($row_data, $row_count % 2 == 0);
        $row_count++;
    }
    
    // Add expenditure totals
    if ($pdf->GetY() > 175) {
        $pdf->AddPage();
    }
    $pdf->Ln(3);
    $pdf->TotalRow('EXPENDITURE', $stats['total_expenditure'], count($expenditure_data), [220, 53, 69]);
}

// Clear the output buffer
ob_end_clean();

// Generate filename
$filter_suffix = '';
$type_suffix = '';

if ($category !== 'all') {
    $filter_suffix = '_' . ucwords(str_replace('_', '', $category));
}

if ($transaction_type !== 'all') {
    $type_suffix = $transaction_type === 'income_only' ? '_IncomeOnly' : '_ExpenditureOnly';
}

$date_suffix = '_' . date('Y-m-d', strtotime($start_date)) . '_to_' . date('Y-m-d', strtotime($end_date));

$filename = 'Expenses_Tracking_Report' . $filter_suffix . $type_suffix . $date_suffix . '.pdf';

// Output PDF
$pdf->Output('D', $filename);
?>