<?php
// controllers/export_float_history.php
// Float History PDF Export Controller
// Prevent any output before PDF generation
ob_start();

require('../config/class.php');
require('../helpers/fpdf/fpdf.php');

class FloatHistoryPDF extends FPDF {
    protected $start_date;
    protected $end_date;
    protected $total_records;
    protected $date_range_days;

    function setFilters($start_date, $end_date, $total_records, $date_range_days) {
        $this->start_date = $start_date;
        $this->end_date = $end_date;
        $this->total_records = $total_records;
        $this->date_range_days = $date_range_days;
    }

    function Header() {
        // Company Header with LATO SACCO styling
        $this->SetFillColor(81, 8, 126); // #51087E
        $this->Rect(0, 0, 210, 25, 'F'); // Full width colored header
        
        // Logo (if available)
        if (file_exists('../public/image/logo.jpg')) {
            $this->Image('../public/image/logo.jpg', 15, 5, 20);
        }
        
        // Company Info
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial','B', 18);
        $this->SetXY(45, 8);
        $this->Cell(150, 8, 'LATO SACCO LIMITED', 0, 1, 'L');
        
        $this->SetFont('Arial','', 12);
        $this->SetXY(45, 16);
        $this->Cell(150, 6, 'Float History Management Report', 0, 1, 'L');
        
        // Report Details Box
        $this->SetY(30);
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','B', 11);
        
        // Report info box
        $this->SetFillColor(248, 249, 252);
        $this->Rect(15, 30, 180, 35, 'F');
        $this->SetXY(20, 35);
        
        // Date Range
        $formatted_start = date('M d, Y', strtotime($this->start_date));
        $formatted_end = date('M d, Y', strtotime($this->end_date));
        $period_text = "Report Period: $formatted_start to $formatted_end";
        $this->Cell(85, 6, $period_text, 0, 0, 'L');
        
        // Record Count
        $this->Cell(85, 6, 'Total Records: ' . $this->total_records, 0, 1, 'R');
        
        $this->SetXY(20, 42);
        $this->Cell(85, 6, 'Generated: ' . date('M d, Y H:i:s'), 0, 0, 'L');
        
        // Days Range
        $this->Cell(85, 6, 'Date Range: ' . $this->date_range_days . ' days', 0, 1, 'R');
        
        $this->SetXY(20, 49);
        $this->SetFont('Arial','', 9);
        $this->SetTextColor(80, 80, 80);
        $this->Cell(85, 6, 'Generated by: ' . ($_SESSION['username'] ?? 'System Administrator'), 0, 0, 'L');
        $this->Cell(85, 6, 'Includes: All float reset transactions', 0, 1, 'R');
        
        $this->SetXY(20, 56);
        $this->Cell(85, 6, 'System: LATO Management System', 0, 0, 'L');
        $this->Cell(85, 6, 'Currency: Kenya Shillings (KSh)', 0, 1, 'R');
        
        $this->Ln(12);
    }
    
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial','I', 8);
        $this->SetTextColor(128, 128, 128);
        
        // Footer line
        $this->Line(15, $this->GetY(), 195, $this->GetY());
        $this->Ln(3);
        
        $this->Cell(0, 6, 'LATO SACCO LIMITED - Confidential Float Management Report', 0, 0, 'L');
        $this->Cell(0, 6, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }

    function ExecutiveSummary($summary) {
        $this->SetFont('Arial','B', 14);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');
        $this->Ln(5);
        
        // Summary boxes in a structured layout
        $box_width = 45;
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(245, 245, 245);
        
        // Row 1 - Main Statistics
        $this->Cell($box_width, 8, 'Total Resets:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($summary['total_resets']), 1, 0, 'R');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Unique Days:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($summary['unique_days']), 1, 1, 'R');
        
        // Row 2 - Amount Analysis
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Highest Closing:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(0, 128, 0); // Green for positive
        $this->Cell($box_width, 8, 'KSh ' . number_format($summary['highest_closing'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Lowest Closing:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(220, 53, 69); // Red for concerning
        $this->Cell($box_width, 8, 'KSh ' . number_format($summary['lowest_closing'], 2), 1, 1, 'R');
        $this->SetTextColor(0, 0, 0);
        
        // Row 3 - Averages and Performance
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Average Closing:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($summary['average_closing'], 2), 1, 0, 'R');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Avg Resets/Day:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($summary['average_resets_per_day'], 1), 1, 1, 'R');
        
        // Row 4 - Financial Performance
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total Fees:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(0, 128, 0);
        $this->Cell($box_width, 8, 'KSh ' . number_format($summary['total_fees_collected'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Net Flow:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $net_color = $summary['net_money_flow_period'] >= 0 ? [0, 128, 0] : [220, 53, 69];
        $this->SetTextColor($net_color[0], $net_color[1], $net_color[2]);
        $this->Cell($box_width, 8, 'KSh ' . number_format($summary['net_money_flow_period'], 2), 1, 1, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->Ln(10);
    }

    function FloatHistoryTableHeader() {
        $this->SetFont('Arial','B', 9);
        $this->SetFillColor(81, 8, 126); // Primary purple
        $this->SetTextColor(255, 255, 255);
        
        $headers = [
            ['text' => 'Date', 'width' => 25],
            ['text' => 'Reset Time', 'width' => 25],
            ['text' => 'Closing Float (KSh)', 'width' => 35],
            ['text' => 'Opening Float (KSh)', 'width' => 35],
            ['text' => 'Money In (KSh)', 'width' => 30],
            ['text' => 'Money Out (KSh)', 'width' => 30],
            ['text' => 'Reset By', 'width' => 25]
        ];
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 8, $header['text'], 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(0, 0, 0);
    }

    function FloatHistoryTableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 7);
        
        // Alternate row colors
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        $this->Cell(25, 7, date('M d, Y', strtotime($data['date'])), 1, 0, 'C', true);
        $this->Cell(25, 7, date('H:i A', strtotime($data['created_at'])), 1, 0, 'C', true);
        
        // Closing float - color code based on amount
        $closing_amount = floatval($data['closing_float']);
        if ($closing_amount > 50000) {
            $this->SetTextColor(0, 128, 0); // Green for high amounts
        } elseif ($closing_amount < 10000) {
            $this->SetTextColor(220, 53, 69); // Red for low amounts
        } else {
            $this->SetTextColor(255, 140, 0); // Orange for medium amounts
        }
        $this->Cell(35, 7, number_format($closing_amount, 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        
        // Opening float
        $opening_amount = floatval($data['opening_float']);
        $this->Cell(35, 7, number_format($opening_amount, 2), 1, 0, 'R', true);
        
        // Money in (green)
        $money_in = floatval($data['total_money_in']) + floatval($data['total_withdrawal_fees']);
        $this->SetTextColor(0, 128, 0);
        $this->Cell(30, 7, number_format($money_in, 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        
        // Money out (red)
        $money_out = floatval($data['total_money_out']);
        $this->SetTextColor(220, 53, 69);
        $this->Cell(30, 7, number_format($money_out, 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(25, 7, substr($data['reset_by_full_name'], 0, 15), 1, 1, 'L', true);
    }

    function DailySummarySection($daily_breakdown) {
        if (empty($daily_breakdown)) return;
        
        $this->SetFont('Arial','B', 12);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'DAILY SUMMARY BREAKDOWN', 0, 1, 'L');
        $this->Ln(3);
        
        // Daily summary table header
        $this->SetFont('Arial','B', 9);
        $this->SetFillColor(52, 58, 64); // Dark gray
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(30, 8, 'Date', 1, 0, 'C', true);
        $this->Cell(20, 8, 'Resets', 1, 0, 'C', true);
        $this->Cell(30, 8, 'Final Closing', 1, 0, 'C', true);
        $this->Cell(30, 8, 'Total Fees', 1, 0, 'C', true);
        $this->Cell(35, 8, 'Money Handled', 1, 0, 'C', true);
        $this->Cell(25, 8, 'First Reset', 1, 0, 'C', true);
        $this->Cell(25, 8, 'Last Reset', 1, 1, 'C', true);
        
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','', 8);
        
        $row_count = 0;
        foreach ($daily_breakdown as $day) {
            if ($row_count % 2 == 0) {
                $this->SetFillColor(248, 249, 252);
            } else {
                $this->SetFillColor(255, 255, 255);
            }
            
            $this->Cell(30, 7, date('M d, Y', strtotime($day['date'])), 1, 0, 'C', true);
            $this->Cell(20, 7, $day['reset_count'], 1, 0, 'C', true);
            
            // Final closing amount with color coding
            $closing = $day['final_closing_float'];
            if ($closing > 50000) {
                $this->SetTextColor(0, 128, 0);
            } elseif ($closing < 10000) {
                $this->SetTextColor(220, 53, 69);
            }
            $this->Cell(30, 7, number_format($closing, 0), 1, 0, 'R', true);
            $this->SetTextColor(0, 0, 0);
            
            $this->Cell(30, 7, number_format($day['total_fees_collected'], 0), 1, 0, 'R', true);
            $this->Cell(35, 7, number_format($day['total_money_handled'], 0), 1, 0, 'R', true);
            $this->Cell(25, 7, date('H:i', strtotime($day['first_reset'])), 1, 0, 'C', true);
            $this->Cell(25, 7, date('H:i', strtotime($day['last_reset'])), 1, 1, 'C', true);
            
            $row_count++;
        }
        
        $this->Ln(5);
    }

    function TotalRow($total_records, $summary) {
        $this->SetFont('Arial','B', 9);
        $this->SetFillColor(81, 8, 126);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(50, 9, 'GRAND TOTALS', 1, 0, 'L', true);
        $this->Cell(35, 9, $total_records . ' Total Resets', 1, 0, 'C', true);
        $this->Cell(35, 9, 'Avg: KSh ' . number_format($summary['average_closing'], 0), 1, 0, 'C', true);
        $this->Cell(30, 9, 'KSh ' . number_format($summary['total_fees_collected'], 0), 1, 0, 'R', true);
        $this->Cell(35, 9, 'Range: ' . $summary['date_range']['days'] . ' days', 1, 1, 'C', true);
        
        $this->SetTextColor(0, 0, 0);
    }
}

// Initialize session and check permissions
session_start();
date_default_timezone_set("Africa/Nairobi");

if (!isset($_SESSION['user_id']) || ($_SESSION['role'] !== 'admin' && $_SESSION['role'] !== 'manager')) {
    http_response_code(403);
    die('Unauthorized access');
}

// Get filter parameters
$days_back = isset($_GET['days']) ? (int)$_GET['days'] : 30;
$days_back = max(1, min(365, $days_back)); // Validate range

// Initialize database
$db = new db_class();

if (!$db->conn) {
    http_response_code(500);
    die('Database connection failed');
}

// Calculate date range
$end_date = date('Y-m-d');
$start_date = date('Y-m-d', strtotime("-{$days_back} days"));

// Get float history data using the same query as the controller
$query = "SELECT 
            fh.history_id,
            fh.date,
            fh.closing_float,
            fh.opening_float,
            fh.total_money_in,
            fh.total_money_out,
            fh.total_withdrawal_fees,
            fh.total_offloaded,
            fh.reset_reason,
            fh.notes,
            fh.created_at,
            u.username as reset_by,
            u.firstname,
            u.lastname,
            CASE 
                WHEN u.firstname IS NOT NULL AND u.lastname IS NOT NULL 
                THEN CONCAT(u.firstname, ' ', u.lastname)
                WHEN u.username IS NOT NULL 
                THEN u.username
                ELSE 'System'
            END as reset_by_full_name
          FROM float_history fh
          LEFT JOIN user u ON fh.reset_by = u.user_id
          WHERE fh.date BETWEEN ? AND ?
          ORDER BY fh.date DESC, fh.created_at DESC";

$stmt = $db->conn->prepare($query);
$stmt->bind_param("ss", $start_date, $end_date);
$stmt->execute();
$result = $stmt->get_result();

$history_data = [];
$daily_summary = [];

while ($row = $result->fetch_assoc()) {
    $history_data[] = $row;
    
    // Build daily summary
    $date_key = $row['date'];
    if (!isset($daily_summary[$date_key])) {
        $daily_summary[$date_key] = [
            'date' => $date_key,
            'reset_count' => 0,
            'first_reset' => $row['created_at'],
            'last_reset' => $row['created_at'],
            'final_closing_float' => (float)$row['closing_float'],
            'total_fees_collected' => 0,
            'total_money_handled' => 0
        ];
    }
    
    $daily_summary[$date_key]['reset_count']++;
    if ($row['created_at'] < $daily_summary[$date_key]['first_reset']) {
        $daily_summary[$date_key]['first_reset'] = $row['created_at'];
    }
    if ($row['created_at'] > $daily_summary[$date_key]['last_reset']) {
        $daily_summary[$date_key]['last_reset'] = $row['created_at'];
        $daily_summary[$date_key]['final_closing_float'] = (float)$row['closing_float'];
    }
    $daily_summary[$date_key]['total_fees_collected'] += (float)$row['total_withdrawal_fees'];
    $daily_summary[$date_key]['total_money_handled'] += (float)$row['total_money_in'] + (float)$row['total_money_out'];
}

$stmt->close();

// Calculate summary statistics
$summary = [];
if (!empty($history_data)) {
    $closing_amounts = array_column($history_data, 'closing_float');
    $closing_amounts = array_map('floatval', $closing_amounts);
    
    $total_fees = array_sum(array_map('floatval', array_column($history_data, 'total_withdrawal_fees')));
    $total_money_in = array_sum(array_map('floatval', array_column($history_data, 'total_money_in')));
    $total_money_out = array_sum(array_map('floatval', array_column($history_data, 'total_money_out')));
    
    $summary = [
        'total_resets' => count($history_data),
        'unique_days' => count($daily_summary),
        'highest_closing' => max($closing_amounts),
        'lowest_closing' => min($closing_amounts),
        'average_closing' => array_sum($closing_amounts) / count($closing_amounts),
        'total_fees_collected' => $total_fees,
        'total_money_in_period' => $total_money_in,
        'total_money_out_period' => $total_money_out,
        'net_money_flow_period' => $total_money_in + $total_fees - $total_money_out,
        'average_resets_per_day' => count($history_data) / max(1, count($daily_summary)),
        'date_range' => [
            'start' => $start_date,
            'end' => $end_date,
            'days' => $days_back
        ],
        'daily_breakdown' => array_values($daily_summary)
    ];
}

// Initialize PDF
$pdf = new FloatHistoryPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->setFilters($start_date, $end_date, count($history_data), $days_back);

// Generate PDF
$pdf->AddPage();

// Add executive summary if we have data
if (!empty($summary)) {
    $pdf->ExecutiveSummary($summary);
}

// Float History Section
if (!empty($history_data)) {
    $pdf->SetFont('Arial','B', 12);
    $pdf->SetTextColor(81, 8, 126);
    $pdf->Cell(0, 10, 'FLOAT RESET HISTORY DETAIL', 0, 1, 'L');
    $pdf->Ln(3);
    
    $pdf->FloatHistoryTableHeader();
    
    $row_count = 0;
    foreach ($history_data as $row_data) {
        // Check if we need a new page
        if ($pdf->GetY() > 250) {
            $pdf->AddPage();
            $pdf->FloatHistoryTableHeader();
        }
        
        $pdf->FloatHistoryTableRow($row_data, $row_count % 2 == 0);
        $row_count++;
    }
    
    // Add totals
    if ($pdf->GetY() > 245) {
        $pdf->AddPage();
    }
    $pdf->Ln(3);
    $pdf->TotalRow(count($history_data), $summary);
    $pdf->Ln(10);
    
    // Add daily summary section
    if (!empty($daily_summary)) {
        if ($pdf->GetY() > 200) {
            $pdf->AddPage();
        }
        $pdf->DailySummarySection($summary['daily_breakdown']);
    }
} else {
    $pdf->SetFont('Arial','', 12);
    $pdf->Cell(0, 20, 'No float history records found for the selected period.', 0, 1, 'C');
}

// Clear the output buffer
ob_end_clean();

// Generate filename
$date_suffix = '_' . date('Y-m-d', strtotime($start_date)) . '_to_' . date('Y-m-d', strtotime($end_date));
$filename = 'Float_History_Report' . $date_suffix . '.pdf';

// Output PDF
$pdf->Output('D', $filename);
?>