<?php
// Prevent any output before PDF generation
ob_start();

require('../config/class.php');
require('../helpers/fpdf/fpdf.php');

class PDF extends FPDF {
    protected $start_date;
    protected $end_date;
    protected $filter_type;

    function setDates($start_date, $end_date, $filter_type = '') {
        $this->start_date = $start_date;
        $this->end_date = $end_date;
        $this->filter_type = $filter_type;
    }

    function Header() {
        // Company Header with better styling
        $this->SetFillColor(81, 8, 126); // #51087E
        $this->Rect(0, 0, 297, 25, 'F'); // Full width colored header
        
        // Logo
        $this->Image('../public/image/mylogo.png', 15, 5, 20);
        
        // Company Info
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial','B', 18);
        $this->SetXY(45, 8);
        $this->Cell(200, 8, 'LATO SACCO LIMITED', 0, 1, 'L');
        
        $this->SetFont('Arial','', 12);
        $this->SetXY(45, 16);
        $this->Cell(200, 6, 'Comprehensive Disbursement Report', 0, 1, 'L');
        
        // Report Details Box
        $this->SetY(30);
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','B', 11);
        
        // Report info box
        $this->SetFillColor(248, 249, 252);
        $this->Rect(15, 30, 267, 30, 'F');
        $this->SetXY(20, 35);
        
        // Date Range and Filter Info
        if ($this->start_date && $this->end_date) {
            $formatted_start = date('M d, Y', strtotime($this->start_date));
            $formatted_end = date('M d, Y', strtotime($this->end_date));
            $period_text = "Report Period: $formatted_start to $formatted_end";
        } else {
            $period_text = "Report Period: All Time";
        }
        
        $this->Cell(130, 6, $period_text, 0, 0, 'L');
        
        // Filter Type with better descriptions
        $filter_text = '';
        switch($this->filter_type) {
            case 'today': 
                $filter_text = 'Filter: Today\'s Records Only'; 
                break;
            case 'yesterday': 
                $filter_text = 'Filter: Yesterday\'s Records Only'; 
                break;
            case 'week': 
                $filter_text = 'Filter: This Week\'s Records Only'; 
                break;
            case 'month': 
                $filter_text = 'Filter: This Month\'s Records Only'; 
                break;
            case 'custom': 
                $filter_text = 'Filter: Custom Date Range Applied'; 
                break;
            default: 
                $filter_text = 'Filter: All Records (No Filter Applied)'; 
                break;
        }
        
        $this->Cell(110, 6, $filter_text, 0, 1, 'R');
        
        $this->SetXY(20, 42);
        $this->Cell(130, 6, 'Generated: ' . date('M d, Y H:i:s'), 0, 0, 'L');
        
        // Show what data is included
        $this->SetFont('Arial','', 9);
        $this->SetTextColor(80, 80, 80);
        $this->Cell(110, 6, 'Includes: Loans & Disbursements matching filter', 0, 1, 'R');
        
        $this->SetXY(20, 49);
        $this->Cell(130, 6, 'Generated by: ' . ($_SESSION['username'] ?? 'System Administrator'), 0, 0, 'L');
        
        // Status filter info
        if (isset($_GET['status']) && $_GET['status'] !== '') {
            $status_text = $_GET['status'] == '1' ? 'Status Filter: Pending Loans Only' : 'Status Filter: Disbursed Loans Only';
            $this->Cell(110, 6, $status_text, 0, 1, 'R');
        } else {
            $this->Cell(110, 6, 'Status Filter: All Statuses Included', 0, 1, 'R');
        }
        
        $this->Ln(10);
    }
    
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial','I', 8);
        $this->SetTextColor(128, 128, 128);
        
        // Footer line
        $this->Line(15, $this->GetY(), 282, $this->GetY());
        $this->Ln(3);
        
        $this->Cell(0, 6, 'LATO SACCO LIMITED - Confidential Report', 0, 0, 'L');
        $this->Cell(0, 6, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }

    function SummarySection($data) {
        $this->SetFont('Arial','B', 14);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');
        $this->Ln(5);
        
        // Summary boxes in a row
        $box_width = 65;
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(245, 245, 245);
        
        // Row 1
        $this->Cell($box_width, 8, 'Total Records:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($data['total_records']), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Pending Loans:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($data['pending_count']), 1, 1, 'C');
        
        // Row 2
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total Amount:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['total_amount'], 2), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Disbursed Count:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($data['disbursed_count']), 1, 1, 'C');
        
        // Row 3
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Pending Amount:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['pending_amount'], 2), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total W/D Fees:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['total_withdrawal_fees'], 2), 1, 1, 'C');
        
        // Row 4
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Disbursed Amount:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['disbursed_amount'], 2), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Net Disbursed:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $net_disbursed = $data['disbursed_amount'] - $data['total_withdrawal_fees'];
        $this->Cell($box_width, 8, 'KSh ' . number_format($net_disbursed, 2), 1, 1, 'C');
        
        $this->Ln(10);
    }

    function TableHeader() {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(81, 8, 126);
        $this->SetTextColor(255, 255, 255);
        
        $headers = [
            ['text' => 'Ref No', 'width' => 22],
            ['text' => 'Borrower Name', 'width' => 35],
            ['text' => 'Status', 'width' => 20],
            ['text' => 'Amount', 'width' => 25],
            ['text' => 'Payment Terms', 'width' => 25],
            ['text' => 'Date Applied', 'width' => 25],
            ['text' => 'Date Approved', 'width' => 25],
            ['text' => 'Disbursed By', 'width' => 30],
            ['text' => 'W/D Fee', 'width' => 20],
            ['text' => 'Date/Time', 'width' => 35]
        ];
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 10, $header['text'], 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(0, 0, 0);
    }

    function TableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 7);
        
        // Alternate row colors
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        // Status color coding
        $status_color = [0, 0, 0]; // default black
        if ($data['status_text'] == 'Disbursed') {
            $status_color = [0, 128, 0]; // green
        } elseif ($data['status_text'] == 'Pending') {
            $status_color = [255, 140, 0]; // orange
        }
        
        $this->Cell(22, 8, $data['ref_no'], 1, 0, 'C', true);
        $this->Cell(35, 8, $data['borrower_name'], 1, 0, 'L', true);
        
        // Status with color
        $this->SetTextColor($status_color[0], $status_color[1], $status_color[2]);
        $this->Cell(20, 8, $data['status_text'], 1, 0, 'C', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(25, 8, $data['amount'], 1, 0, 'R', true);
        $this->Cell(25, 8, $data['payment_terms'], 1, 0, 'C', true);
        $this->Cell(25, 8, $data['date_applied'], 1, 0, 'C', true);
        $this->Cell(25, 8, $data['date_approved'], 1, 0, 'C', true);
        $this->Cell(30, 8, $data['disbursed_by'], 1, 0, 'L', true);
        $this->Cell(20, 8, $data['withdrawal_fee'], 1, 0, 'R', true);
        $this->Cell(35, 8, $data['datetime'], 1, 1, 'C', true);
    }

    function TotalRow($totals) {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(81, 8, 126);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(22, 10, 'TOTALS', 1, 0, 'C', true);
        $this->Cell(35, 10, $totals['count'] . ' Records', 1, 0, 'C', true);
        $this->Cell(20, 10, '-', 1, 0, 'C', true);
        $this->Cell(25, 10, 'KSh ' . number_format($totals['total_amount'], 0), 1, 0, 'R', true);
        $this->Cell(25, 10, '-', 1, 0, 'C', true);
        $this->Cell(25, 10, '-', 1, 0, 'C', true);
        $this->Cell(25, 10, '-', 1, 0, 'C', true);
        $this->Cell(30, 10, '-', 1, 0, 'C', true);
        $this->Cell(20, 10, 'KSh ' . number_format($totals['total_fees'], 0), 1, 0, 'R', true);
        $this->Cell(35, 10, '-', 1, 1, 'C', true);
        
        $this->SetTextColor(0, 0, 0);
    }
}

// Get filter parameters
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : '';
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : '';
$quick_filter = isset($_GET['quick_filter']) ? $_GET['quick_filter'] : '';
$status_filter = isset($_GET['status']) ? $_GET['status'] : '';

// Initialize PDF
$pdf = new PDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->setDates($start_date, $end_date, $quick_filter);

$db = new db_class();

// Build WHERE clause based on filters
$where_conditions = [];
$params = [];
$param_types = '';

// Handle date filters - FIXED LOGIC
if ($quick_filter) {
    switch ($quick_filter) {
        case 'today':
            // For status 1 (pending), filter by date_applied; for status 3+ (disbursed), filter by disbursement date
            if ($status_filter == '1') {
                $where_conditions[] = "DATE(l.date_applied) = CURDATE()";
            } elseif ($status_filter == '3') {
                $where_conditions[] = "DATE(p.date_created) = CURDATE()";
            } else {
                $where_conditions[] = "(DATE(l.date_applied) = CURDATE() OR DATE(p.date_created) = CURDATE())";
            }
            break;
        case 'yesterday':
            if ($status_filter == '1') {
                $where_conditions[] = "DATE(l.date_applied) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
            } elseif ($status_filter == '3') {
                $where_conditions[] = "DATE(p.date_created) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
            } else {
                $where_conditions[] = "(DATE(l.date_applied) = DATE_SUB(CURDATE(), INTERVAL 1 DAY) OR DATE(p.date_created) = DATE_SUB(CURDATE(), INTERVAL 1 DAY))";
            }
            break;
        case 'week':
            if ($status_filter == '1') {
                $where_conditions[] = "YEARWEEK(l.date_applied, 1) = YEARWEEK(CURDATE(), 1)";
            } elseif ($status_filter == '3') {
                $where_conditions[] = "YEARWEEK(p.date_created, 1) = YEARWEEK(CURDATE(), 1)";
            } else {
                $where_conditions[] = "(YEARWEEK(l.date_applied, 1) = YEARWEEK(CURDATE(), 1) OR YEARWEEK(p.date_created, 1) = YEARWEEK(CURDATE(), 1))";
            }
            break;
        case 'month':
            if ($status_filter == '1') {
                $where_conditions[] = "YEAR(l.date_applied) = YEAR(CURDATE()) AND MONTH(l.date_applied) = MONTH(CURDATE())";
            } elseif ($status_filter == '3') {
                $where_conditions[] = "YEAR(p.date_created) = YEAR(CURDATE()) AND MONTH(p.date_created) = MONTH(CURDATE())";
            } else {
                $where_conditions[] = "((YEAR(l.date_applied) = YEAR(CURDATE()) AND MONTH(l.date_applied) = MONTH(CURDATE())) OR (YEAR(p.date_created) = YEAR(CURDATE()) AND MONTH(p.date_created) = MONTH(CURDATE())))";
            }
            break;
        case 'custom':
            if ($start_date && $end_date) {
                if ($status_filter == '1') {
                    $where_conditions[] = "DATE(l.date_applied) BETWEEN ? AND ?";
                    $params[] = $start_date;
                    $params[] = $end_date;
                    $param_types .= 'ss';
                } elseif ($status_filter == '3') {
                    $where_conditions[] = "DATE(p.date_created) BETWEEN ? AND ?";
                    $params[] = $start_date;
                    $params[] = $end_date;
                    $param_types .= 'ss';
                } else {
                    $where_conditions[] = "(DATE(l.date_applied) BETWEEN ? AND ? OR DATE(p.date_created) BETWEEN ? AND ?)";
                    $params[] = $start_date;
                    $params[] = $end_date;
                    $params[] = $start_date;
                    $params[] = $end_date;
                    $param_types .= 'ssss';
                }
            } elseif ($start_date) {
                if ($status_filter == '1') {
                    $where_conditions[] = "DATE(l.date_applied) >= ?";
                    $params[] = $start_date;
                    $param_types .= 's';
                } elseif ($status_filter == '3') {
                    $where_conditions[] = "DATE(p.date_created) >= ?";
                    $params[] = $start_date;
                    $param_types .= 's';
                } else {
                    $where_conditions[] = "(DATE(l.date_applied) >= ? OR DATE(p.date_created) >= ?)";
                    $params[] = $start_date;
                    $params[] = $start_date;
                    $param_types .= 'ss';
                }
            } elseif ($end_date) {
                if ($status_filter == '1') {
                    $where_conditions[] = "DATE(l.date_applied) <= ?";
                    $params[] = $end_date;
                    $param_types .= 's';
                } elseif ($status_filter == '3') {
                    $where_conditions[] = "DATE(p.date_created) <= ?";
                    $params[] = $end_date;
                    $param_types .= 's';
                } else {
                    $where_conditions[] = "(DATE(l.date_applied) <= ? OR DATE(p.date_created) <= ?)";
                    $params[] = $end_date;
                    $params[] = $end_date;
                    $param_types .= 'ss';
                }
            }
            break;
    }
}

// Apply status filter - FIXED LOGIC
if ($status_filter !== '') {
    $where_conditions[] = "l.status = ?";
    $params[] = $status_filter;
    $param_types .= 'i';
}

$where_clause = !empty($where_conditions) ? 'WHERE ' . implode(' AND ', $where_conditions) : '';

// FIXED MAIN QUERY - Use appropriate JOIN based on status filter
if ($status_filter == '1') {
    // For pending loans, we don't need payment data
    $main_query = "SELECT 
        l.ref_no,
        CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
        l.status,
        l.amount,
        l.loan_term,
        l.monthly_payment,
        l.date_applied,
        COALESCE(l.date_released, l.date_approved) as date_approved,
        NULL as withdrawal_fee,
        NULL as disbursement_date,
        NULL as disbursed_by,
        NULL as receipt_no
        FROM loan l
        INNER JOIN client_accounts c ON l.account_id = c.account_id
        $where_clause
        ORDER BY l.date_applied DESC, l.ref_no";
} elseif ($status_filter !== '' && $status_filter != '1') {
    // For disbursed loans, we need payment data, so use INNER JOIN
    $main_query = "SELECT 
        l.ref_no,
        CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
        l.status,
        l.amount,
        l.loan_term,
        l.monthly_payment,
        l.date_applied,
        COALESCE(l.date_released, l.date_approved) as date_approved,
        p.withdrawal_fee,
        p.date_created as disbursement_date,
        u.username as disbursed_by,
        p.receipt_no
        FROM loan l
        INNER JOIN client_accounts c ON l.account_id = c.account_id
        INNER JOIN payment p ON l.loan_id = p.loan_id
        LEFT JOIN user u ON p.user_id = u.user_id
        $where_clause
        ORDER BY p.date_created DESC, l.ref_no";
} else {
    // For all statuses, use LEFT JOIN as in original
    $main_query = "SELECT 
        l.ref_no,
        CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
        l.status,
        l.amount,
        l.loan_term,
        l.monthly_payment,
        l.date_applied,
        COALESCE(l.date_released, l.date_approved) as date_approved,
        p.withdrawal_fee,
        p.date_created as disbursement_date,
        u.username as disbursed_by,
        p.receipt_no
        FROM loan l
        INNER JOIN client_accounts c ON l.account_id = c.account_id
        LEFT JOIN payment p ON l.loan_id = p.loan_id
        LEFT JOIN user u ON p.user_id = u.user_id
        $where_clause
        ORDER BY 
            CASE WHEN p.date_created IS NOT NULL THEN p.date_created ELSE l.date_applied END DESC, 
            l.ref_no";
}

$stmt = $db->conn->prepare($main_query);
if (!empty($params)) {
    $stmt->bind_param($param_types, ...$params);
}
$stmt->execute();
$results = $stmt->get_result();

// Calculate summary statistics
$total_amount = 0;
$total_withdrawal_fees = 0;
$pending_amount = 0;
$disbursed_amount = 0;
$pending_count = 0;
$disbursed_count = 0;
$total_records = 0;

$all_data = [];
while ($row = $results->fetch_assoc()) {
    $total_records++;
    $total_amount += $row['amount'];
    
    if ($row['status'] == 1) { // Pending
        $pending_amount += $row['amount'];
        $pending_count++;
        $status_text = 'Pending';
    } else { // Disbursed
        $disbursed_amount += $row['amount'];
        $disbursed_count++;
        $status_text = 'Disbursed';
        $total_withdrawal_fees += $row['withdrawal_fee'] ?? 0;
    }
    
    // Format data for display
    $formatted_row = [
        'ref_no' => $row['ref_no'],
        'borrower_name' => strlen($row['borrower_name']) > 25 ? substr($row['borrower_name'], 0, 22) . '...' : $row['borrower_name'],
        'status_text' => $status_text,
        'amount' => 'KSh ' . number_format($row['amount'], 0),
        'payment_terms' => $row['loan_term'] ? $row['loan_term'] . 'm/' . number_format($row['monthly_payment'], 0) : '-',
        'date_applied' => date('M d, Y', strtotime($row['date_applied'])),
        'date_approved' => $row['date_approved'] ? date('M d, Y', strtotime($row['date_approved'])) : '-',
        'disbursed_by' => $row['disbursed_by'] ? (strlen($row['disbursed_by']) > 20 ? substr($row['disbursed_by'], 0, 17) . '...' : $row['disbursed_by']) : '-',
        'withdrawal_fee' => $row['withdrawal_fee'] ? 'KSh ' . number_format($row['withdrawal_fee'], 0) : '-',
        'datetime' => $row['disbursement_date'] ? date('M d, Y H:i', strtotime($row['disbursement_date'])) : '-'
    ];
    
    $all_data[] = $formatted_row;
}

// Summary data
$summary_data = [
    'total_records' => $total_records,
    'pending_count' => $pending_count,
    'disbursed_count' => $disbursed_count,
    'total_amount' => $total_amount,
    'pending_amount' => $pending_amount,
    'disbursed_amount' => $disbursed_amount,
    'total_withdrawal_fees' => $total_withdrawal_fees
];

// Start generating PDF
$pdf->AddPage();

// Add summary section
$pdf->SummarySection($summary_data);

// Add table header
$pdf->SetFont('Arial','B', 12);
$pdf->SetTextColor(81, 8, 126);
$pdf->Cell(0, 10, 'DETAILED LOAN RECORDS', 0, 1, 'L');
$pdf->Ln(5);

$pdf->TableHeader();

// Add table rows
$row_count = 0;
foreach ($all_data as $row_data) {
    // Check if we need a new page
    if ($pdf->GetY() > 180) {
        $pdf->AddPage();
        $pdf->TableHeader();
    }
    
    $pdf->TableRow($row_data, $row_count % 2 == 0);
    $row_count++;
}

// Add totals row
$totals = [
    'count' => $total_records,
    'total_amount' => $total_amount,
    'total_fees' => $total_withdrawal_fees
];

if ($pdf->GetY() > 175) {
    $pdf->AddPage();
}

$pdf->Ln(5);
$pdf->TotalRow($totals);

// Clear the output buffer
ob_end_clean();

// Generate filename with clear filter indication
$filter_suffix = '';
$status_suffix = '';

if ($quick_filter) {
    switch($quick_filter) {
        case 'today': $filter_suffix = '_Today'; break;
        case 'yesterday': $filter_suffix = '_Yesterday'; break;
        case 'week': $filter_suffix = '_ThisWeek'; break;
        case 'month': $filter_suffix = '_ThisMonth'; break;
        case 'custom': $filter_suffix = '_CustomRange'; break;
    }
}

if ($status_filter !== '') {
    $status_suffix = $status_filter == '1' ? '_PendingOnly' : '_DisbursedOnly';
}

if ($start_date && $end_date && $quick_filter == 'custom') {
    $date_suffix = '_' . date('Y-m-d', strtotime($start_date)) . '_to_' . date('Y-m-d', strtotime($end_date));
} else {
    $date_suffix = '_' . date('Y-m-d');
}

$filename = 'Disbursement_Report' . $filter_suffix . $status_suffix . $date_suffix . '.pdf';

// Output PDF
$pdf->Output('D', $filename);
?>