<?php
// Prevent any output before PDF generation
ob_start();

// Start session to get user info
session_start();

require('../config/class.php');
require('../helpers/fpdf/fpdf.php');

class PDF extends FPDF {
    protected $start_date;
    protected $end_date;
    protected $filter_type;
    protected $status_filter;

    function setFilterInfo($start_date, $end_date, $filter_type = '', $status_filter = '') {
        $this->start_date = $start_date;
        $this->end_date = $end_date;
        $this->filter_type = $filter_type;
        $this->status_filter = $status_filter;
    }

    function Header() {
        // Company Header with better styling
        $this->SetFillColor(81, 8, 126); // #51087E
        $this->Rect(0, 0, 297, 25, 'F'); // Full width colored header
        
        // Logo
        $this->Image('../public/image/mylogo.png', 15, 5, 20);
        
        // Company Info
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial','B', 18);
        $this->SetXY(45, 8);
        $this->Cell(200, 8, 'LATO SACCO LIMITED', 0, 1, 'L');
        
        $this->SetFont('Arial','', 12);
        $this->SetXY(45, 16);
        $this->Cell(200, 6, 'Comprehensive Disbursement Report', 0, 1, 'L');
        
        // Report Details Box
        $this->SetY(30);
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','B', 11);
        
        // Report info box
        $this->SetFillColor(248, 249, 252);
        $this->Rect(15, 30, 267, 35, 'F');
        $this->SetXY(20, 35);
        
        // Date Range and Filter Info
        $period_text = $this->getFilterDescription();
        
        $this->Cell(130, 6, $period_text, 0, 0, 'L');
        
        // Filter Type with better descriptions
        $filter_text = $this->getFilterTypeText();
        
        $this->SetFont('Arial','B', 10);
        $this->Cell(110, 6, $filter_text, 0, 1, 'R');
        
        $this->SetXY(20, 42);
        $this->SetFont('Arial','B', 11);
        $this->Cell(130, 6, 'Generated: ' . date('M d, Y H:i:s'), 0, 0, 'L');
        
        // Status filter info
        $status_text = $this->getStatusFilterText();
        $this->SetFont('Arial','B', 10);
        $this->Cell(110, 6, $status_text, 0, 1, 'R');
        
        $this->SetXY(20, 49);
        $this->SetFont('Arial','B', 11);
        $this->Cell(130, 6, 'Generated by: ' . ($_SESSION['username'] ?? 'System Admin'), 0, 0, 'L');
        
        // Show what data is included
        $this->SetFont('Arial','I', 9);
        $this->SetTextColor(80, 80, 80);
        $this->Cell(110, 6, 'Report reflects applied filters only', 0, 1, 'R');
        
        $this->SetXY(20, 56);
        $this->SetFont('Arial','', 9);
        $this->Cell(130, 6, 'Report ID: ' . date('YmdHis'), 0, 0, 'L');
        
        $this->Ln(10);
    }
    
    private function getFilterDescription() {
        if ($this->start_date && $this->end_date) {
            $formatted_start = date('M d, Y', strtotime($this->start_date));
            $formatted_end = date('M d, Y', strtotime($this->end_date));
            return "Period: $formatted_start to $formatted_end";
        }
        
        switch($this->filter_type) {
            case 'today': 
                return "Period: Today (" . date('M d, Y') . ")"; 
            case 'yesterday': 
                return "Period: Yesterday (" . date('M d, Y', strtotime('-1 day')) . ")"; 
            case 'week': 
                $week_start = date('M d', strtotime('monday this week'));
                $week_end = date('M d, Y', strtotime('sunday this week'));
                return "Period: This Week ($week_start - $week_end)"; 
            case 'month': 
                return "Period: This Month (" . date('F Y') . ")"; 
            default: 
                return "Period: All Time (No Date Filter)"; 
        }
    }
    
    private function getFilterTypeText() {
        switch($this->filter_type) {
            case 'today': 
                return "Filter: Today's Records"; 
            case 'yesterday': 
                return "Filter: Yesterday's Records"; 
            case 'week': 
                return "Filter: This Week's Records"; 
            case 'month': 
                return "Filter: This Month's Records"; 
            case 'custom': 
                return "Filter: Custom Date Range"; 
            default: 
                return "Filter: All Available Records"; 
        }
    }
    
    private function getStatusFilterText() {
        if ($this->status_filter === '1') {
            return "Status: Pending Loans Only";
        } elseif ($this->status_filter === '3' || $this->status_filter === '2') {
            return "Status: Disbursed Loans Only";
        } else {
            return "Status: All Loan Statuses";
        }
    }
    
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial','I', 8);
        $this->SetTextColor(128, 128, 128);
        
        // Footer line
        $this->Line(15, $this->GetY(), 282, $this->GetY());
        $this->Ln(3);
        
        $this->Cell(0, 6, 'LATO SACCO LIMITED - Confidential Report', 0, 0, 'L');
        $this->Cell(0, 6, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }

    function SummarySection($data) {
        $this->SetFont('Arial','B', 14);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');
        $this->Ln(3);
        
        // Add filter notice
        $this->SetFont('Arial','I', 9);
        $this->SetTextColor(200, 50, 50);
        $this->Cell(0, 5, 'Note: This summary reflects ONLY the filtered data based on your selected criteria', 0, 1, 'L');
        $this->Ln(3);
        
        // Summary boxes in a row
        $box_width = 65;
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(245, 245, 245);
        $this->SetTextColor(0, 0, 0);
        
        // Row 1
        $this->Cell($box_width, 8, 'Total Records:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($data['total_records']), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Pending Loans:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($data['pending_count']), 1, 1, 'C');
        
        // Row 2
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total Amount:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['total_amount'], 2), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Disbursed Count:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($data['disbursed_count']), 1, 1, 'C');
        
        // Row 3
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Pending Amount:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['pending_amount'], 2), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total W/D Fees:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['total_withdrawal_fees'], 2), 1, 1, 'C');
        
        // Row 4
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Disbursed Amount:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, 'KSh ' . number_format($data['disbursed_amount'], 2), 1, 0, 'C');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Net Disbursed:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $net_disbursed = $data['disbursed_amount'] - $data['total_withdrawal_fees'];
        $this->Cell($box_width, 8, 'KSh ' . number_format($net_disbursed, 2), 1, 1, 'C');
        
        $this->Ln(10);
    }

    function TableHeader() {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(81, 8, 126);
        $this->SetTextColor(255, 255, 255);
        
        $headers = [
            ['text' => 'Ref No', 'width' => 22],
            ['text' => 'Borrower Name', 'width' => 35],
            ['text' => 'Status', 'width' => 20],
            ['text' => 'Amount', 'width' => 25],
            ['text' => 'Payment Terms', 'width' => 25],
            ['text' => 'Date Applied', 'width' => 25],
            ['text' => 'Date Approved', 'width' => 25],
            ['text' => 'Disbursed By', 'width' => 30],
            ['text' => 'W/D Fee', 'width' => 20],
            ['text' => 'Date/Time', 'width' => 35]
        ];
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 10, $header['text'], 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(0, 0, 0);
    }

    function TableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 7);
        
        // Alternate row colors
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        // Status color coding
        $status_color = [0, 0, 0]; // default black
        if ($data['status_text'] == 'Disbursed') {
            $status_color = [0, 128, 0]; // green
        } elseif ($data['status_text'] == 'Pending') {
            $status_color = [255, 140, 0]; // orange
        }
        
        $this->Cell(22, 8, $data['ref_no'], 1, 0, 'C', true);
        $this->Cell(35, 8, $data['borrower_name'], 1, 0, 'L', true);
        
        // Status with color
        $this->SetTextColor($status_color[0], $status_color[1], $status_color[2]);
        $this->Cell(20, 8, $data['status_text'], 1, 0, 'C', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(25, 8, $data['amount'], 1, 0, 'R', true);
        $this->Cell(25, 8, $data['payment_terms'], 1, 0, 'C', true);
        $this->Cell(25, 8, $data['date_applied'], 1, 0, 'C', true);
        $this->Cell(25, 8, $data['date_approved'], 1, 0, 'C', true);
        $this->Cell(30, 8, $data['disbursed_by'], 1, 0, 'L', true);
        $this->Cell(20, 8, $data['withdrawal_fee'], 1, 0, 'R', true);
        $this->Cell(35, 8, $data['datetime'], 1, 1, 'C', true);
    }

    function TotalRow($totals) {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(81, 8, 126);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(22, 10, 'TOTALS', 1, 0, 'C', true);
        $this->Cell(35, 10, $totals['count'] . ' Records', 1, 0, 'C', true);
        $this->Cell(20, 10, '-', 1, 0, 'C', true);
        $this->Cell(25, 10, 'KSh ' . number_format($totals['total_amount'], 0), 1, 0, 'R', true);
        $this->Cell(25, 10, '-', 1, 0, 'C', true);
        $this->Cell(25, 10, '-', 1, 0, 'C', true);
        $this->Cell(25, 10, '-', 1, 0, 'C', true);
        $this->Cell(30, 10, '-', 1, 0, 'C', true);
        $this->Cell(20, 10, 'KSh ' . number_format($totals['total_fees'], 0), 1, 0, 'R', true);
        $this->Cell(35, 10, '-', 1, 1, 'C', true);
        
        $this->SetTextColor(0, 0, 0);
    }
}

// Get filter parameters
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : '';
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : '';
$quick_filter = isset($_GET['quick_filter']) ? $_GET['quick_filter'] : '';
$status_filter = isset($_GET['status']) ? $_GET['status'] : '';

// Initialize PDF
$pdf = new PDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->setFilterInfo($start_date, $end_date, $quick_filter, $status_filter);

$db = new db_class();

// Build WHERE clause based on filters - EXACTLY AS IN disbursement.php
$loan_where_conditions = [];
$payment_where_conditions = [];
$loan_params = [];
$payment_params = [];
$loan_types = "";
$payment_types = "";

// Handle date filters - EXACTLY AS IN disbursement.php
if ($quick_filter) {
    switch ($quick_filter) {
        case 'today':
            $loan_where_conditions[] = "DATE(l.date_applied) = CURDATE()";
            $payment_where_conditions[] = "DATE(p.date_created) = CURDATE()";
            break;
        case 'yesterday':
            $loan_where_conditions[] = "DATE(l.date_applied) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
            $payment_where_conditions[] = "DATE(p.date_created) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
            break;
        case 'week':
            $loan_where_conditions[] = "YEARWEEK(l.date_applied, 1) = YEARWEEK(CURDATE(), 1)";
            $payment_where_conditions[] = "YEARWEEK(p.date_created, 1) = YEARWEEK(CURDATE(), 1)";
            break;
        case 'month':
            $loan_where_conditions[] = "YEAR(l.date_applied) = YEAR(CURDATE()) AND MONTH(l.date_applied) = MONTH(CURDATE())";
            $payment_where_conditions[] = "YEAR(p.date_created) = YEAR(CURDATE()) AND MONTH(p.date_created) = MONTH(CURDATE())";
            break;
        case 'custom':
            if (!empty($start_date)) {
                $loan_where_conditions[] = "DATE(l.date_applied) >= ?";
                $payment_where_conditions[] = "DATE(p.date_created) >= ?";
                $loan_params[] = $start_date;
                $payment_params[] = $start_date;
                $loan_types .= "s";
                $payment_types .= "s";
            }
            if (!empty($end_date)) {
                $loan_where_conditions[] = "DATE(l.date_applied) <= ?";
                $payment_where_conditions[] = "DATE(p.date_created) <= ?";
                $loan_params[] = $end_date;
                $payment_params[] = $end_date;
                $loan_types .= "s";
                $payment_types .= "s";
            }
            break;
    }
}

// Add status filter - EXACTLY AS IN disbursement.php
if ($status_filter !== '') {
    $loan_where_conditions[] = "l.status = ?";
    $loan_params[] = $status_filter;
    $loan_types .= "i";
}

// Build WHERE clauses
$loan_where_clause = !empty($loan_where_conditions) ? 'WHERE ' . implode(' AND ', $loan_where_conditions) : '';

// MAIN QUERY - Using same logic as disbursement.php
if ($status_filter == '1') {
    // Pending loans only - no payment data needed
    $main_query = "SELECT 
        l.ref_no,
        CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
        l.status,
        l.amount,
        l.loan_term,
        l.monthly_payment,
        l.date_applied,
        COALESCE(l.date_released, l.date_approved, l.date_applied) as date_approved,
        NULL as withdrawal_fee,
        NULL as disbursement_date,
        NULL as disbursed_by
        FROM loan l
        INNER JOIN client_accounts c ON l.account_id = c.account_id
        $loan_where_clause
        ORDER BY l.date_applied DESC, l.ref_no";
        
    $stmt = $db->conn->prepare($main_query);
    if (!empty($loan_params)) {
        $stmt->bind_param($loan_types, ...$loan_params);
    }
} elseif ($status_filter !== '' && $status_filter != '1') {
    // Disbursed loans only - need payment data
    $payment_where_clause = !empty($payment_where_conditions) ? 'WHERE ' . implode(' AND ', $payment_where_conditions) : '';
    
    // If we have both loan and payment conditions, combine them
    if ($loan_where_clause && $payment_where_clause) {
        $combined_where = str_replace('WHERE ', '', $loan_where_clause) . ' AND ' . str_replace('WHERE ', '', $payment_where_clause);
        $combined_where = 'WHERE ' . $combined_where;
    } elseif ($loan_where_clause) {
        $combined_where = $loan_where_clause;
    } elseif ($payment_where_clause) {
        $combined_where = $payment_where_clause;
    } else {
        $combined_where = '';
    }
    
    $main_query = "SELECT 
        l.ref_no,
        CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
        l.status,
        l.amount,
        l.loan_term,
        l.monthly_payment,
        l.date_applied,
        COALESCE(l.date_released, l.date_approved) as date_approved,
        p.withdrawal_fee,
        p.date_created as disbursement_date,
        u.username as disbursed_by
        FROM loan l
        INNER JOIN client_accounts c ON l.account_id = c.account_id
        INNER JOIN payment p ON l.loan_id = p.loan_id
        LEFT JOIN user u ON p.user_id = u.user_id
        $combined_where
        ORDER BY p.date_created DESC, l.ref_no";
    
    // Combine parameters
    $combined_params = array_merge($loan_params, $payment_params);
    $combined_types = $loan_types . $payment_types;
    
    $stmt = $db->conn->prepare($main_query);
    if (!empty($combined_params)) {
        $stmt->bind_param($combined_types, ...$combined_params);
    }
} else {
    // All statuses - include both pending and disbursed
    $payment_where_clause = !empty($payment_where_conditions) ? str_replace('WHERE ', '', implode(' AND ', $payment_where_conditions)) : '';
    
    if ($loan_where_clause && $payment_where_clause) {
        $combined_where = str_replace('WHERE ', '', $loan_where_clause);
        $main_query = "SELECT 
            l.ref_no,
            CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
            l.status,
            l.amount,
            l.loan_term,
            l.monthly_payment,
            l.date_applied,
            COALESCE(l.date_released, l.date_approved) as date_approved,
            p.withdrawal_fee,
            p.date_created as disbursement_date,
            u.username as disbursed_by
            FROM loan l
            INNER JOIN client_accounts c ON l.account_id = c.account_id
            LEFT JOIN payment p ON l.loan_id = p.loan_id AND ($payment_where_clause)
            LEFT JOIN user u ON p.user_id = u.user_id
            WHERE $combined_where
            ORDER BY COALESCE(p.date_created, l.date_applied) DESC, l.ref_no";
        
        $combined_params = array_merge($loan_params, $payment_params);
        $combined_types = $loan_types . $payment_types;
    } else {
        $main_query = "SELECT 
            l.ref_no,
            CONCAT(c.first_name, ' ', c.last_name) as borrower_name,
            l.status,
            l.amount,
            l.loan_term,
            l.monthly_payment,
            l.date_applied,
            COALESCE(l.date_released, l.date_approved) as date_approved,
            p.withdrawal_fee,
            p.date_created as disbursement_date,
            u.username as disbursed_by
            FROM loan l
            INNER JOIN client_accounts c ON l.account_id = c.account_id
            LEFT JOIN payment p ON l.loan_id = p.loan_id
            LEFT JOIN user u ON p.user_id = u.user_id
            $loan_where_clause
            ORDER BY COALESCE(p.date_created, l.date_applied) DESC, l.ref_no";
        
        $combined_params = $loan_params;
        $combined_types = $loan_types;
    }
    
    $stmt = $db->conn->prepare($main_query);
    if (!empty($combined_params)) {
        $stmt->bind_param($combined_types, ...$combined_params);
    }
}

$stmt->execute();
$results = $stmt->get_result();

// Calculate summary statistics
$total_amount = 0;
$total_withdrawal_fees = 0;
$pending_amount = 0;
$disbursed_amount = 0;
$pending_count = 0;
$disbursed_count = 0;
$total_records = 0;

$all_data = [];
while ($row = $results->fetch_assoc()) {
    $total_records++;
    $total_amount += $row['amount'];
    
    if ($row['status'] == 1) { // Pending
        $pending_amount += $row['amount'];
        $pending_count++;
        $status_text = 'Pending';
    } else { // Disbursed
        $disbursed_amount += $row['amount'];
        $disbursed_count++;
        $status_text = 'Disbursed';
        $total_withdrawal_fees += $row['withdrawal_fee'] ?? 0;
    }
    
    // Format data for display
    $formatted_row = [
        'ref_no' => $row['ref_no'],
        'borrower_name' => strlen($row['borrower_name']) > 25 ? substr($row['borrower_name'], 0, 22) . '...' : $row['borrower_name'],
        'status_text' => $status_text,
        'amount' => 'KSh ' . number_format($row['amount'], 0),
        'payment_terms' => $row['loan_term'] ? $row['loan_term'] . 'm/' . number_format($row['monthly_payment'], 0) : '-',
        'date_applied' => date('M d, Y', strtotime($row['date_applied'])),
        'date_approved' => $row['date_approved'] ? date('M d, Y', strtotime($row['date_approved'])) : '-',
        'disbursed_by' => $row['disbursed_by'] ? (strlen($row['disbursed_by']) > 20 ? substr($row['disbursed_by'], 0, 17) . '...' : $row['disbursed_by']) : '-',
        'withdrawal_fee' => $row['withdrawal_fee'] ? 'KSh ' . number_format($row['withdrawal_fee'], 0) : '-',
        'datetime' => $row['disbursement_date'] ? date('M d, Y H:i', strtotime($row['disbursement_date'])) : '-'
    ];
    
    $all_data[] = $formatted_row;
}

// Summary data
$summary_data = [
    'total_records' => $total_records,
    'pending_count' => $pending_count,
    'disbursed_count' => $disbursed_count,
    'total_amount' => $total_amount,
    'pending_amount' => $pending_amount,
    'disbursed_amount' => $disbursed_amount,
    'total_withdrawal_fees' => $total_withdrawal_fees
];

// Start generating PDF
$pdf->AddPage();

// Add summary section
$pdf->SummarySection($summary_data);

// Add table header
$pdf->SetFont('Arial','B', 12);
$pdf->SetTextColor(81, 8, 126);
$pdf->Cell(0, 10, 'DETAILED LOAN RECORDS', 0, 1, 'L');
$pdf->Ln(5);

$pdf->TableHeader();

// Add table rows
$row_count = 0;
foreach ($all_data as $row_data) {
    // Check if we need a new page
    if ($pdf->GetY() > 180) {
        $pdf->AddPage();
        $pdf->TableHeader();
    }
    
    $pdf->TableRow($row_data, $row_count % 2 == 0);
    $row_count++;
}

// Add totals row
$totals = [
    'count' => $total_records,
    'total_amount' => $total_amount,
    'total_fees' => $total_withdrawal_fees
];

if ($pdf->GetY() > 175) {
    $pdf->AddPage();
}

$pdf->Ln(5);
$pdf->TotalRow($totals);

// Clear the output buffer
ob_end_clean();

// Generate filename with clear filter indication
$filter_suffix = '';
$status_suffix = '';

if ($quick_filter) {
    switch($quick_filter) {
        case 'today': $filter_suffix = '_Today'; break;
        case 'yesterday': $filter_suffix = '_Yesterday'; break;
        case 'week': $filter_suffix = '_ThisWeek'; break;
        case 'month': $filter_suffix = '_ThisMonth'; break;
        case 'custom': $filter_suffix = '_CustomRange'; break;
    }
}

if ($status_filter !== '') {
    $status_suffix = $status_filter == '1' ? '_PendingOnly' : '_DisbursedOnly';
}

if ($start_date && $end_date && $quick_filter == 'custom') {
    $date_suffix = '_' . date('Ymd', strtotime($start_date)) . '_to_' . date('Ymd', strtotime($end_date));
} else {
    $date_suffix = '_' . date('Ymd');
}

$filename = 'Disbursement_Report' . $filter_suffix . $status_suffix . $date_suffix . '.pdf';

// Output PDF
$pdf->Output('D', $filename);
?>