<?php
// controllers/generate_general_report_pdf.php
// Prevent any output before PDF generation
ob_start();

date_default_timezone_set("Africa/Nairobi");
require_once '../helpers/session.php';
require('../config/class.php');
require('../helpers/fpdf/fpdf.php');

// Check if user is logged in
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] !== 'admin' && $_SESSION['role'] !== 'manager')) {
    $_SESSION['error_msg'] = "Unauthorized access";
    header('Location: ../views/index.php');
    exit();
}

// Import components
require_once '../components/general_reporting/financial_utilities.php';
require_once '../components/general_reporting/debit.php';
require_once '../components/general_reporting/credit.php';

class GeneralReportPDF extends FPDF {
    protected $start_date;
    protected $end_date;
    protected $filter_type;
    protected $opening_date;

    function setFilters($start_date, $end_date, $filter_type, $opening_date) {
        $this->start_date = $start_date;
        $this->end_date = $end_date;
        $this->filter_type = $filter_type;
        $this->opening_date = $opening_date;
    }

    function Header() {
        // Company Header with LATO SACCO styling
        $this->SetFillColor(81, 8, 126); // #51087E
        $this->Rect(0, 0, 297, 25, 'F');
        
        // Logo (if available)
        if (file_exists('../public/image/logo.jpg')) {
            $this->Image('../public/image/logo.jpg', 15, 5, 20);
        }
        
        // Company Info
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial','B', 18);
        $this->SetXY(45, 8);
        $this->Cell(200, 8, 'LATO SACCO LIMITED', 0, 1, 'L');
        
        $this->SetFont('Arial','', 12);
        $this->SetXY(45, 16);
        $this->Cell(200, 6, 'General Financial Report - Income & Expenditure', 0, 1, 'L');
        
        // Report Details Box
        $this->SetY(30);
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','B', 11);
        
        $this->SetFillColor(248, 249, 252);
        $this->Rect(15, 30, 267, 28, 'F');
        $this->SetXY(20, 35);
        
        // Date Range
        $formatted_start = date('M d, Y', strtotime($this->start_date));
        $formatted_end = date('M d, Y', strtotime($this->end_date));
        $this->Cell(130, 6, "Period: $formatted_start to $formatted_end", 0, 0, 'L');
        
        // Filter Type
        $filter_text = 'Report Type: ';
        switch($this->filter_type) {
            case 'debit': 
                $filter_text .= 'Debit Only (Income)'; 
                break;
            case 'credit': 
                $filter_text .= 'Credit Only (Expenses)'; 
                break;
            default: 
                $filter_text .= 'Complete (Debit & Credit)'; 
                break;
        }
        $this->Cell(110, 6, $filter_text, 0, 1, 'R');
        
        $this->SetXY(20, 42);
        $this->Cell(130, 6, 'Generated: ' . date('M d, Y H:i:s'), 0, 0, 'L');
        $this->Cell(110, 6, 'Generated by: ' . ($_SESSION['username'] ?? 'System'), 0, 1, 'R');
        
        $this->SetXY(20, 49);
        $this->SetFont('Arial','', 9);
        $this->SetTextColor(80, 80, 80);
        $this->Cell(130, 6, 'Opening Balance: ' . date('M d, Y', strtotime($this->opening_date)), 0, 0, 'L');
        $this->Cell(110, 6, 'Currency: Kenya Shillings (KSh)', 0, 1, 'R');
        
        $this->Ln(12);
    }
    
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial','I', 8);
        $this->SetTextColor(128, 128, 128);
        
        $this->Line(15, $this->GetY(), 282, $this->GetY());
        $this->Ln(3);
        
        $this->Cell(0, 6, 'LATO SACCO LIMITED - Confidential Financial Report', 0, 0, 'L');
        $this->Cell(0, 6, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }

    function ExecutiveSummary($total_debit, $total_credit, $net_position) {
        $this->SetFont('Arial','B', 14);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');
        $this->Ln(5);
        
        $box_width = 88;
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(245, 245, 245);
        
        // Debit
        if ($this->filter_type !== 'credit') {
            $this->Cell($box_width, 8, 'Total Debit (Income):', 1, 0, 'L', true);
            $this->SetFont('Arial','', 10);
            $this->SetTextColor(0, 128, 0);
            $this->Cell($box_width, 8, 'KSh ' . number_format($total_debit, 2), 1, 0, 'R');
            $this->SetTextColor(0, 0, 0);
        }
        
        // Credit
        if ($this->filter_type !== 'debit') {
            if ($this->filter_type === 'all') {
                $this->SetFont('Arial','B', 10);
            }
            $this->Cell($box_width, 8, 'Total Credit (Expenses):', 1, 0, 'L', true);
            $this->SetFont('Arial','', 10);
            $this->SetTextColor(220, 53, 69);
            $this->Cell($box_width - ($this->filter_type === 'all' ? 0 : $box_width), 8, 'KSh ' . number_format($total_credit, 2), 1, 1, 'R');
            $this->SetTextColor(0, 0, 0);
        } else {
            $this->Ln();
        }
        
        // Net Position (only for 'all')
        if ($this->filter_type === 'all') {
            $this->SetFont('Arial','B', 10);
            $is_profit = $net_position > 0;
            $this->Cell($box_width, 8, 'Net Position (' . ($is_profit ? 'Profit' : 'Loss') . '):', 1, 0, 'L', true);
            $this->SetFont('Arial','', 10);
            $color = $is_profit ? [0, 128, 0] : [220, 53, 69];
            $this->SetTextColor($color[0], $color[1], $color[2]);
            $this->Cell($box_width * 2, 8, 'KSh ' . number_format($net_position, 2), 1, 1, 'R');
            $this->SetTextColor(0, 0, 0);
        }
        
        $this->Ln(10);
    }

    function DebitTableHeader() {
        $this->SetFont('Arial','B', 7);
        $this->SetFillColor(40, 167, 69);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(30, 6, 'DEBIT', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Opening', 1, 0, 'C', true);
        $this->Cell(40, 6, 'Category', 1, 0, 'C', true);
        $this->Cell(30, 6, 'Amount (KSh)', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Transaction', 1, 0, 'C', true);
        $this->Cell(40, 6, 'Category', 1, 0, 'C', true);
        $this->Cell(30, 6, 'Amount (KSh)', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Closing', 1, 0, 'C', true);
        $this->Cell(40, 6, 'Category', 1, 0, 'C', true);
        $this->Cell(17, 6, 'Amount', 1, 1, 'C', true);
        $this->SetTextColor(0, 0, 0);
    }

    function DebitTableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 6);
        
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        $this->Cell(30, 6, '', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Balance', 1, 0, 'C', true);
        $this->Cell(40, 6, substr($data['name'], 0, 25), 1, 0, 'L', true);
        $this->Cell(30, 6, number_format($data['opening_balance'], 2), 1, 0, 'R', true);
        $this->Cell(25, 6, 'Period', 1, 0, 'C', true);
        $this->Cell(40, 6, substr($data['name'], 0, 25), 1, 0, 'L', true);
        $this->SetTextColor(0, 128, 0);
        $this->Cell(30, 6, number_format($data['transactions'], 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        $this->Cell(25, 6, 'Balance', 1, 0, 'C', true);
        $this->Cell(40, 6, substr($data['name'], 0, 25), 1, 0, 'L', true);
        $this->Cell(17, 6, number_format($data['closing_balance'], 2), 1, 1, 'R', true);
    }

    function CreditTableHeader() {
        $this->SetFont('Arial','B', 7);
        $this->SetFillColor(220, 53, 69);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(30, 6, 'CREDIT', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Opening', 1, 0, 'C', true);
        $this->Cell(40, 6, 'Category', 1, 0, 'C', true);
        $this->Cell(30, 6, 'Amount (KSh)', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Transaction', 1, 0, 'C', true);
        $this->Cell(40, 6, 'Category', 1, 0, 'C', true);
        $this->Cell(30, 6, 'Amount (KSh)', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Closing', 1, 0, 'C', true);
        $this->Cell(40, 6, 'Category', 1, 0, 'C', true);
        $this->Cell(17, 6, 'Amount', 1, 1, 'C', true);
        $this->SetTextColor(0, 0, 0);
    }

    function CreditTableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 6);
        
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        $this->Cell(30, 6, '', 1, 0, 'C', true);
        $this->Cell(25, 6, 'Balance', 1, 0, 'C', true);
        $this->Cell(40, 6, substr($data['category'], 0, 25), 1, 0, 'L', true);
        $this->Cell(30, 6, number_format($data['opening_balance'], 2), 1, 0, 'R', true);
        $this->Cell(25, 6, 'Period', 1, 0, 'C', true);
        $this->Cell(40, 6, substr($data['category'], 0, 25), 1, 0, 'L', true);
        $this->SetTextColor(220, 53, 69);
        $this->Cell(30, 6, number_format($data['transactions'], 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        $this->Cell(25, 6, 'Balance', 1, 0, 'C', true);
        $this->Cell(40, 6, substr($data['category'], 0, 25), 1, 0, 'L', true);
        $this->Cell(17, 6, number_format($data['closing_balance'], 2), 1, 1, 'R', true);
    }

    function TotalRow($label, $total_amount, $color_rgb) {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor($color_rgb[0], $color_rgb[1], $color_rgb[2]);
        $this->SetTextColor(255, 255, 255);
        
        $this->Cell(95, 8, $label . ' TOTALS', 1, 0, 'L', true);
        $this->Cell(30, 8, 'KSh ' . number_format($total_amount, 2), 1, 0, 'R', true);
        $this->Cell(95, 8, '', 1, 0, 'C', true);
        $this->Cell(30, 8, 'KSh ' . number_format($total_amount, 2), 1, 0, 'R', true);
        $this->Cell(52, 8, '', 1, 1, 'C', true);
        
        $this->SetTextColor(0, 0, 0);
    }
}

// Get filter parameters
$filters = FinancialUtilities::initializeFilters();
$start_date = $filters['start_date'];
$end_date = $filters['end_date'];
$filter_type = $filters['filter_type'];
$opening_date = $filters['opening_date'];

// Initialize database and calculators
$db = new db_class();
$debitCalc = new DebitCalculator($db, $start_date, $end_date, $opening_date);
$creditCalc = new CreditCalculator($db, $start_date, $end_date, $opening_date);

// Get data
$debit_data = $debitCalc->getDebitData();
$credit_data = $creditCalc->getCreditData();
$total_debit = $debitCalc->getTotalDebit();
$total_credit = $creditCalc->getTotalCredit();
$net_position = $total_debit - $total_credit;

// Initialize PDF
$pdf = new GeneralReportPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->setFilters($start_date, $end_date, $filter_type, $opening_date);

// Start generating PDF
$pdf->AddPage();

// Add executive summary
$pdf->ExecutiveSummary($total_debit, $total_credit, $net_position);

// Debit Section
if ($filter_type !== 'credit' && !empty($debit_data)) {
    $pdf->SetFont('Arial','B', 12);
    $pdf->SetTextColor(40, 167, 69);
    $pdf->Cell(0, 10, 'DEBIT - INCOME SOURCES', 0, 1, 'L');
    $pdf->Ln(3);
    
    $pdf->DebitTableHeader();
    
    $row_count = 0;
    foreach ($debit_data as $row_data) {
        if ($pdf->GetY() > 180) {
            $pdf->AddPage();
            $pdf->DebitTableHeader();
        }
        
        $pdf->DebitTableRow($row_data, $row_count % 2 == 0);
        $row_count++;
    }
    
    if ($pdf->GetY() > 175) {
        $pdf->AddPage();
    }
    $pdf->Ln(3);
    $pdf->TotalRow('DEBIT', $total_debit, [40, 167, 69]);
    $pdf->Ln(10);
}

// Credit Section
if ($filter_type !== 'debit' && !empty($credit_data)) {
    $pdf->SetFont('Arial','B', 12);
    $pdf->SetTextColor(220, 53, 69);
    $pdf->Cell(0, 10, 'CREDIT - EXPENSE CATEGORIES', 0, 1, 'L');
    $pdf->Ln(3);
    
    $pdf->CreditTableHeader();
    
    $row_count = 0;
    foreach ($credit_data as $row_data) {
        if ($pdf->GetY() > 180) {
            $pdf->AddPage();
            $pdf->CreditTableHeader();
        }
        
        $pdf->CreditTableRow($row_data, $row_count % 2 == 0);
        $row_count++;
    }
    
    if ($pdf->GetY() > 175) {
        $pdf->AddPage();
    }
    $pdf->Ln(3);
    $pdf->TotalRow('CREDIT', $total_credit, [220, 53, 69]);
}

// Clear the output buffer
ob_end_clean();

// Generate filename
$filter_suffix = '';
switch($filter_type) {
    case 'debit': 
        $filter_suffix = '_DebitOnly'; 
        break;
    case 'credit': 
        $filter_suffix = '_CreditOnly'; 
        break;
}

$date_suffix = '_' . date('Ymd', strtotime($start_date)) . '_to_' . date('Ymd', strtotime($end_date));
$filename = 'General_Financial_Report' . $filter_suffix . $date_suffix . '.pdf';

// Output PDF
$pdf->Output('D', $filename);
?>