<?php
// Enhanced Expense Report Generator
// Prevent any output before PDF generation
ob_start();

// Error reporting for debugging
ini_set('display_errors', 1);
error_reporting(E_ALL);

// Start session and set timezone
session_start();
date_default_timezone_set("Africa/Nairobi");

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    die("Unauthorized access");
}

// Required files
require_once __DIR__ . '/../config/class.php';
require_once __DIR__ . '/../helpers/fpdf/fpdf.php';

class EnhancedExpensePDF extends FPDF {
    protected $filters;
    protected $stats;
    
    function __construct($orientation = 'L', $unit = 'mm', $size = 'A4') {
        parent::__construct($orientation, $unit, $size);
        $this->filters = [];
        $this->stats = [];
    }

    function setFilters($filters) {
        $this->filters = $filters;
    }

    function setStats($stats) {
        $this->stats = $stats;
    }

    function Header() {
        // Company Header with LATO SACCO styling
        $this->SetFillColor(81, 8, 126); // #51087E
        $this->Rect(0, 0, 297, 25, 'F'); // Full width colored header
        
        // Logo (if available)
        if (file_exists(__DIR__ . '/../public/image/logo.jpg')) {
            $this->Image(__DIR__ . '/../public/image/logo.jpg', 15, 5, 20);
        }
        
        // Company Info
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial','B', 18);
        $this->SetXY(45, 8);
        $this->Cell(200, 8, 'LATO SACCO LIMITED', 0, 1, 'L');
        
        $this->SetFont('Arial','', 12);
        $this->SetXY(45, 16);
        $this->Cell(200, 6, 'Financial Transactions Report', 0, 1, 'L');
        
        // Report Details Box
        $this->SetY(30);
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('Arial','B', 11);
        
        // Report info box
        $this->SetFillColor(248, 249, 252);
        $this->Rect(15, 30, 267, 35, 'F');
        $this->SetXY(20, 35);
        
        // Date Range and Filters
        $this->Cell(130, 6, 'Report Period: ' . $this->filters['period_text'], 0, 0, 'L');
        
        // Transaction Type Filter
        $type_text = '';
        switch($this->filters['transaction_type']) {
            case 'expenses': 
                $type_text = 'Filter: Expenses Only'; 
                break;
            case 'received': 
                $type_text = 'Filter: Money Received Only'; 
                break;
            default: 
                $type_text = 'Filter: All Transaction Types'; 
                break;
        }
        $this->Cell(110, 6, $type_text, 0, 1, 'R');
        
        $this->SetXY(20, 42);
        $this->Cell(130, 6, 'Generated: ' . date('M d, Y H:i:s'), 0, 0, 'L');
        $this->Cell(110, 6, 'Total Records: ' . $this->filters['total_records'], 0, 1, 'R');
        
        $this->SetXY(20, 49);
        $this->SetFont('Arial','', 9);
        $this->SetTextColor(80, 80, 80);
        $this->Cell(130, 6, 'Generated by: ' . ($_SESSION['username'] ?? 'System Administrator'), 0, 0, 'L');
        $this->Cell(110, 6, 'Currency: Kenya Shillings (KSh)', 0, 1, 'R');
        
        $this->SetXY(20, 56);
        $this->Cell(130, 6, 'System: LATO Management System', 0, 0, 'L');
        $this->Cell(110, 6, 'Status: ' . ucfirst($this->filters['status']), 0, 1, 'R');
        
        $this->Ln(12);
    }
    
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial','I', 8);
        $this->SetTextColor(128, 128, 128);
        
        // Footer line
        $this->Line(15, $this->GetY(), 282, $this->GetY());
        $this->Ln(3);
        
        $this->Cell(0, 6, 'LATO SACCO LIMITED - Confidential Financial Report', 0, 0, 'L');
        $this->Cell(0, 6, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
    }

    function ExecutiveSummary() {
        $this->SetFont('Arial','B', 14);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L');
        $this->Ln(5);
        
        // Summary boxes in a structured layout
        $box_width = 65;
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(245, 245, 245);
        
        // Row 1 - Main Totals
        $this->Cell($box_width, 8, 'Total Expenses:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(220, 53, 69); // Red for expenses
        $this->Cell($box_width, 8, 'KSh ' . number_format($this->stats['total_expenses'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Total Received:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->SetTextColor(0, 128, 0); // Green for received
        $this->Cell($box_width, 8, 'KSh ' . number_format($this->stats['total_received'], 2), 1, 1, 'R');
        $this->SetTextColor(0, 0, 0);
        
        // Row 2 - Analysis
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Net Balance:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $net_color = $this->stats['net_balance'] >= 0 ? [0, 128, 0] : [220, 53, 69];
        $this->SetTextColor($net_color[0], $net_color[1], $net_color[2]);
        $this->Cell($box_width, 8, 'KSh ' . number_format($this->stats['net_balance'], 2), 1, 0, 'R');
        $this->SetTextColor(0, 0, 0);
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Transaction Count:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $this->Cell($box_width, 8, number_format($this->stats['total_count']), 1, 1, 'R');
        
        // Row 3 - Percentages
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Expense Ratio:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $total_amount = $this->stats['total_expenses'] + $this->stats['total_received'];
        $expense_ratio = $total_amount > 0 ? ($this->stats['total_expenses'] / $total_amount) * 100 : 0;
        $this->Cell($box_width, 8, number_format($expense_ratio, 1) . '%', 1, 0, 'R');
        
        $this->SetFont('Arial','B', 10);
        $this->Cell($box_width, 8, 'Income Ratio:', 1, 0, 'L', true);
        $this->SetFont('Arial','', 10);
        $income_ratio = $total_amount > 0 ? ($this->stats['total_received'] / $total_amount) * 100 : 0;
        $this->Cell($box_width, 8, number_format($income_ratio, 1) . '%', 1, 1, 'R');
        
        $this->Ln(10);
    }

    function CategoryBreakdown($category_totals) {
        $this->SetFont('Arial','B', 12);
        $this->SetTextColor(81, 8, 126);
        $this->Cell(0, 10, 'CATEGORY BREAKDOWN', 0, 1, 'L');
        $this->Ln(3);
        
        // Headers
        $this->SetFont('Arial','B', 10);
        $this->SetFillColor(240, 240, 240);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(80, 8, 'Category', 1, 0, 'L', true);
        $this->Cell(40, 8, 'Amount (KSh)', 1, 0, 'R', true);
        $this->Cell(30, 8, 'Count', 1, 0, 'C', true);
        $this->Cell(30, 8, 'Percentage', 1, 1, 'R', true);
        
        // Data rows
        $this->SetFont('Arial','', 9);
        $total_amount = array_sum(array_column($category_totals, 'amount'));
        
        foreach ($category_totals as $category => $data) {
            $percentage = $total_amount > 0 ? ($data['amount'] / $total_amount) * 100 : 0;
            
            $this->Cell(80, 7, $category, 1, 0, 'L');
            
            // Color based on amount sign
            $amount_color = $data['amount'] >= 0 ? [0, 128, 0] : [220, 53, 69];
            $this->SetTextColor($amount_color[0], $amount_color[1], $amount_color[2]);
            $this->Cell(40, 7, number_format(abs($data['amount']), 2), 1, 0, 'R');
            $this->SetTextColor(0, 0, 0);
            
            $this->Cell(30, 7, number_format($data['count']), 1, 0, 'C');
            $this->Cell(30, 7, number_format($percentage, 1) . '%', 1, 1, 'R');
        }
        
        $this->Ln(10);
    }

    function TransactionTableHeader() {
        $this->SetFont('Arial','B', 8);
        $this->SetFillColor(81, 8, 126);
        $this->SetTextColor(255, 255, 255);
        
        $headers = [
            ['text' => 'Date', 'width' => 22],
            ['text' => 'Receipt No', 'width' => 25],
            ['text' => 'Category', 'width' => 35],
            ['text' => 'Expense Name', 'width' => 40],
            ['text' => 'Description', 'width' => 45],
            ['text' => 'Amount (KSh)', 'width' => 28],
            ['text' => 'Payment Method', 'width' => 25],
            ['text' => 'Status', 'width' => 20],
            ['text' => 'Created By', 'width' => 22]
        ];
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 8, $header['text'], 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(0, 0, 0);
    }

    function TransactionTableRow($data, $is_even = false) {
        $this->SetFont('Arial','', 7);
        
        // Alternate row colors
        if ($is_even) {
            $this->SetFillColor(248, 249, 252);
        } else {
            $this->SetFillColor(255, 255, 255);
        }
        
        $this->Cell(22, 7, date('M d, Y', strtotime($data['date'])), 1, 0, 'C', true);
        $this->Cell(25, 7, substr($data['receipt_no'], 0, 12), 1, 0, 'C', true);
        $this->Cell(35, 7, substr($data['main_category'] ?? 'N/A', 0, 18), 1, 0, 'L', true);
        $this->Cell(40, 7, substr($data['expense_name'] ?? $data['category'], 0, 20), 1, 0, 'L', true);
        $this->Cell(45, 7, substr($data['description'] ?? '', 0, 25), 1, 0, 'L', true);
        
        // Amount with color coding
        $amount = abs($data['amount']);
        if ($data['status'] === 'received') {
            $this->SetTextColor(0, 128, 0); // Green for received
        } else {
            $this->SetTextColor(220, 53, 69); // Red for expenses
        }
        $this->Cell(28, 7, number_format($amount, 2), 1, 0, 'R', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(25, 7, substr($data['payment_method'] ?? 'Cash', 0, 12), 1, 0, 'C', true);
        
        // Status with color coding
        $status_text = $data['status'] === 'received' ? 'Received' : 'Expense';
        $status_color = $data['status'] === 'received' ? [0, 128, 0] : [220, 53, 69];
        $this->SetTextColor($status_color[0], $status_color[1], $status_color[2]);
        $this->Cell(20, 7, $status_text, 1, 0, 'C', true);
        $this->SetTextColor(0, 0, 0);
        
        $this->Cell(22, 7, substr($data['created_by_name'] ?? 'N/A', 0, 12), 1, 1, 'L', true);
    }
}

try {
    // Initialize database connection
    $db = new db_class();

    // Get and validate parameters
    $transaction_type = isset($_GET['transaction_type']) ? $_GET['transaction_type'] : 'all';
    $date_range = isset($_GET['date_range']) ? $_GET['date_range'] : 'all';
    $start_date = isset($_GET['start_date']) ? $_GET['start_date'] : '';
    $end_date = isset($_GET['end_date']) ? $_GET['end_date'] : '';

    // Determine period text for report
    $period_text = 'All Time';
    switch ($date_range) {
        case 'today':
            $period_text = 'Today (' . date('Y-m-d') . ')';
            break;
        case 'week':
            $period_text = 'This Week (' . date('M d') . ' - ' . date('M d, Y') . ')';
            break;
        case 'month':
            $period_text = 'This Month (' . date('F Y') . ')';
            break;
        case 'year':
            $period_text = 'This Year (' . date('Y') . ')';
            break;
        case 'custom':
            if ($start_date && $end_date) {
                $period_text = date('M d, Y', strtotime($start_date)) . ' to ' . date('M d, Y', strtotime($end_date));
            }
            break;
    }

    // Build comprehensive query with expense names
    $query = "SELECT 
        e.id,
        e.date,
        e.receipt_no,
        ec.category as main_category,
        e.category as expense_name,
        e.description,
        e.amount,
        e.payment_method,
        e.status,
        e.remarks,
        u.username as created_by_name,
        e.created_at
    FROM expenses e 
    LEFT JOIN expenses_categories ec ON e.category = ec.name 
    LEFT JOIN user u ON e.created_by = u.user_id
    WHERE 1=1";

    $params = [];
    $types = '';

    // Add filters
    if ($transaction_type !== 'all') {
        $query .= " AND e.status = ?";
        $params[] = ($transaction_type === 'expenses') ? 'completed' : 'received';
        $types .= 's';
    }

    if ($date_range !== 'all') {
        switch ($date_range) {
            case 'today':
                $query .= " AND DATE(e.date) = CURDATE()";
                break;
            case 'week':
                $query .= " AND YEARWEEK(e.date, 1) = YEARWEEK(CURDATE(), 1)";
                break;
            case 'month':
                $query .= " AND YEAR(e.date) = YEAR(CURDATE()) AND MONTH(e.date) = MONTH(CURDATE())";
                break;
            case 'year':
                $query .= " AND YEAR(e.date) = YEAR(CURDATE())";
                break;
            case 'custom':
                if ($start_date && $end_date) {
                    $query .= " AND DATE(e.date) BETWEEN ? AND ?";
                    $params[] = $start_date;
                    $params[] = $end_date;
                    $types .= 'ss';
                }
                break;
        }
    }

    $query .= " ORDER BY e.date DESC, e.created_at DESC";

    // Execute query
    $stmt = $db->conn->prepare($query);
    if (!empty($params)) {
        $stmt->bind_param($types, ...$params);
    }
    $stmt->execute();
    $result = $stmt->get_result();

    if (!$result) {
        throw new Exception("Query failed: " . $db->conn->error);
    }

    // Process data
    $total_expenses = 0;
    $total_received = 0;
    $category_totals = [];
    $transactions = [];
    $total_count = 0;

    while ($row = $result->fetch_assoc()) {
        $transactions[] = $row;
        $total_count++;
        
        if ($row['status'] === 'received') {
            $total_received += $row['amount'];
        } else {
            $total_expenses += abs($row['amount']);
        }
        
        // Category analysis
        $category = $row['main_category'] ?? 'Uncategorized';
        if (!isset($category_totals[$category])) {
            $category_totals[$category] = ['amount' => 0, 'count' => 0];
        }
        
        $amount = $row['status'] === 'received' ? $row['amount'] : -abs($row['amount']);
        $category_totals[$category]['amount'] += $amount;
        $category_totals[$category]['count']++;
    }

    // Calculate statistics
    $net_balance = $total_received - $total_expenses;
    $stats = [
        'total_expenses' => $total_expenses,
        'total_received' => $total_received,
        'net_balance' => $net_balance,
        'total_count' => $total_count
    ];

    // Prepare filters for PDF
    $filters = [
        'period_text' => $period_text,
        'transaction_type' => $transaction_type,
        'total_records' => $total_count,
        'status' => $transaction_type === 'all' ? 'all transactions' : $transaction_type
    ];

    // Create Enhanced PDF
    $pdf = new EnhancedExpensePDF();
    $pdf->setFilters($filters);
    $pdf->setStats($stats);
    $pdf->AliasNbPages();
    $pdf->AddPage();

    // Add executive summary
    $pdf->ExecutiveSummary();

    // Add category breakdown if there are categories
    if (!empty($category_totals)) {
        $pdf->CategoryBreakdown($category_totals);
    }

    // Add detailed transactions
    if (!empty($transactions)) {
        $pdf->AddPage();
        $pdf->SetFont('Arial','B', 12);
        $pdf->SetTextColor(81, 8, 126);
        $pdf->Cell(0, 10, 'DETAILED TRANSACTIONS', 0, 1, 'L');
        $pdf->Ln(3);
        
        $pdf->TransactionTableHeader();
        
        $row_count = 0;
        foreach ($transactions as $transaction) {
            // Check if we need a new page
            if ($pdf->GetY() > 180) {
                $pdf->AddPage();
                $pdf->TransactionTableHeader();
            }
            
            $pdf->TransactionTableRow($transaction, $row_count % 2 == 0);
            $row_count++;
        }
    }

    // Clear the output buffer
    ob_end_clean();

    // Generate filename
    $type_suffix = '';
    if ($transaction_type !== 'all') {
        $type_suffix = $transaction_type === 'expenses' ? '_ExpensesOnly' : '_ReceivedOnly';
    }

    $date_suffix = '';
    if ($date_range === 'custom' && $start_date && $end_date) {
        $date_suffix = '_' . date('Y-m-d', strtotime($start_date)) . '_to_' . date('Y-m-d', strtotime($end_date));
    } else {
        $date_suffix = '_' . ucfirst($date_range) . '_' . date('Y-m-d');
    }

    $filename = 'LATO_Financial_Report' . $type_suffix . $date_suffix . '.pdf';

    // Output PDF
    $pdf->Output('D', $filename);

} catch (Exception $e) {
    // Clear any output
    ob_end_clean();
    
    error_log("Error generating expense report: " . $e->getMessage());
    
    // Return to the page with an error message
    $_SESSION['error_msg'] = 'Failed to generate report. Please try again later.';
    header('Location: ../views/manage_expenses.php');
    exit;
}
?>